{
 "title": "crypto-trader",
 "time": { "from": "2018-03-04T21:13:57.483Z", "to": "2019-05-16T23:33:36.399Z" },
 "templating": {
  "list": [
   { "name": "trader", "query": "MACD-ETH-BTC" },
   {
    "name": "base",
    "query": "SHOW TAG VALUES WITH KEY = \"base\""
   },
   {
    "name": "quote",
    "query": "SHOW TAG VALUES WITH KEY = \"quote\""
   },
   {
    "name": "exchange",
    "query": "SHOW TAG VALUES WITH KEY = \"exchange\""
   },
   { "name": "indicators", "query": "show field KEYS from INPUTS" }
  ]
 },
 "panels": [
  {
   "title": "Profit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "PORTFOLIO",
     "select": [
      [
       { "params": [ "currentProfit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$trader$/" }
     ]
    }
   ]
  },
  {
   "title": "Hold profit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "PORTFOLIO",
     "select": [
      [
       { "params": [ "holdProfit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$trader$/" }
     ]
    }
   ]
  },
  {
   "title": "% trade win",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "PORTFOLIO",
     "select": [
      [
       { "params": [ "percentTradeWin" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$trader$/" }
     ]
    }
   ]
  },
  {
   "title": "Portfolio ${trader}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "totalValue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PORTFOLIO",
     "select": [
      [
       { "params": [ "totalValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$trader$/" }
     ]
    },
    {
     "alias": "currentCapital",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PORTFOLIO",
     "select": [
      [
       { "params": [ "currentCapital" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$trader$/" }
     ]
    },
    {
     "alias": "assetCapital",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PORTFOLIO",
     "select": [
      [
       { "params": [ "assetCapital" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$trader$/" }
     ]
    },
    {
     "alias": "fees",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PORTFOLIO",
     "select": [
      [
       { "params": [ "fees" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$trader$/" }
     ]
    }
   ]
  },
  {
   "title": "${base}/${quote}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "prices",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "OHLC_FILLED",
     "select": [
      [
       { "params": [ "close" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "quote", "operator": "=~", "value": "/^$quote$/" },
      { "condition": "AND", "key": "base", "operator": "=~", "value": "/^$base$/" }
     ]
    },
    {
     "alias": "buy",
     "measurement": "TRADES",
     "select": [
      [
       { "params": [ "price" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$trader$/" },
      { "condition": "AND", "key": "side", "operator": "=", "value": "buy" }
     ]
    },
    {
     "alias": "sell",
     "measurement": "TRADES",
     "select": [
      [
       { "params": [ "price" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$trader$/" },
      { "condition": "AND", "key": "side", "operator": "=", "value": "sell" }
     ]
    }
   ]
  },
  {
   "title": "MACD",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "INPUTS",
     "select": [
      [
       { "params": [ "macd2-MACD" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "macd2" ], "type": "alias" }
      ],
      [
       { "params": [ "macd2-signal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "signal2" ], "type": "alias" }
      ],
      [
       { "params": [ "macd-MACD" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "macd1" ], "type": "alias" }
      ],
      [
       { "params": [ "macd-signal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "signal1" ], "type": "alias" }
      ],
      [
       { "params": [ "macd3-MACD" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "macd3" ], "type": "alias" }
      ],
      [
       { "params": [ "macd3-signal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "signal3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$trader$/" }
     ]
    },
    {
     "alias": "close",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "OHLC_FILLED",
     "select": [
      [
       { "params": [ "close" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "base", "operator": "=~", "value": "/^$base$/" },
      { "condition": "AND", "key": "exchange", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "quote", "operator": "=~", "value": "/^$quote$/" }
     ]
    }
   ]
  },
  {
   "title": "SMA",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "INPUTS",
     "select": [
      [
       { "params": [ "sma15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "sma15m" ], "type": "alias" }
      ],
      [
       { "params": [ "sma1h" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "sma1h" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$trader$/" }
     ]
    },
    {
     "alias": "close",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "OHLC_FILLED",
     "select": [
      [
       { "params": [ "close" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "base", "operator": "=~", "value": "/^$base$/" },
      { "condition": "AND", "key": "exchange", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "quote", "operator": "=~", "value": "/^$quote$/" }
     ]
    }
   ]
  }
 ]
}